apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: ws-www
spec:
  environments:
    - name: production
      build:
        from: master
    - name: development
      build:
        from: feature1
  components:
    - name: www
      src: ./www
      ports:
       - name: http
         port: 3001
      public: true
      monitoring: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "96Mi"
          cpu: "200m"
      replicas: 1
      environmentVariables:
        - environment: production
          variables:
            PORT: 3001
            NODE_ENV: "production"
            ECHO_URL: "http://echo:3000"
        - environment: development
          variables:
            PORT: 3001
            NODE_ENV: "development"
            ECHO_URL: "http://echo:3000"
    - name: echo
      src: ./echo
      ports:
      - name: http
        port: 3000
      public: false
      monitoring: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "96Mi"
          cpu: "200m"
      replicas: 4
      environmentVariables:
        - environment: production
          variables:
            PORT: 3000
            NODE_ENV: "production"
        - environment: development
          variables:
            PORT: 3000
            NODE_ENV: "development"
  dnsAppAlias:
    environment: production
    component: www
