apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: ws-www-vslatten
spec:
  environments:
    - name: production
      build:
        from: master
  components:
    - name: echo
      src: ./echo
      ports:
      - name: http
        port: 3000
      public: false
      monitoring: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "150m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      replicas: 4
      environmentVariables:
        - environment: production
          variables:
            PORT: 3000
            NODE_ENV: "production"
      # secrets:
      #   - MY_SUPER_SECRET
    - name: www
      src: ./www
      ports:
       - name: http
         port: 3001
      public: true
      monitoring: false
      resources:
        requests:
          memory: "64Mi"
          cpu: "400m"
        limits:
          memory: "128Mi"
          cpu: "600m"
      replicas: 1
      environmentVariables:
        - environment: production
          variables:
            PORT: 3001
            NODE_ENV: "production"
            ECHO_URL: "http://echo:3000"
  dnsAppAlias:
    environment: production
    component: www
